# Generated by Django 5.2.1 on 2025-07-01 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flotaApp', '0003_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='observaciones',
        ),
    ]
