# Generated by Django 5.2.1 on 2025-07-03 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flotaApp', '0004_remove_ruta_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'Mantenimiento Preventivo'), ('CORRECTIVO', 'Mantenimiento Correctivo'), ('REVISION_TECNICA', 'Revisión Técnica'), ('CAMBIO_ACEITE', 'Cambio de Aceite'), ('CAMBIO_NEUMATICOS', 'Cambio de Neumáticos'), ('CAMBIO_FRENOS', 'Cambio de Frenos'), ('REPARACION_MOTOR', 'Reparación de Motor'), ('REPARACION_TRANSMISION', 'Reparación de Transmisión'), ('OTROS', 'Otros')], max_length=25, verbose_name='Tipo de Mantenimiento')),
                ('taller', models.CharField(max_length=255, verbose_name='Taller')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo (CLP)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción Detallada')),
                ('estado', models.CharField(choices=[('PROGRAMADO', 'Programado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PROGRAMADO', max_length=15, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flotaApp.conductor', verbose_name='Conductor Responsable')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flotaApp.vehiculo', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Mantención',
                'verbose_name_plural': 'Mantenciones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
